### PR TITLE
php image upload code is added

### PR DESCRIPTION
**Pull request by syedtalaljilani**
I solve the issue [Example] PHP - Script for uploading images #66 I create a file name as imageupload.php in the we can pass filename of image or URL of image and then this image will upload on cloudinary in this example I store local image on cloudinary

### CODE REVIEW

**Comment by syedtalaljilani** [comment]
@colbyfayock check this

**Comment by colbyfayock** [comment]
@syedtalaljilani we're close! a few edit requests. please update this PR instead of creating a new one as its easier to keep our conversation history

* please add `*.sln` to the root `.gitignore` as i would expect that to be a local project file, not something that should be in the repository
* you should not commit your API key and secret inside of imageupload.php - i would recommend that you reset your API key and secret as you would likely now consider them compromised being available on the web
* as far as setting the API Key and Secret, is there a solution for you to be able to create a `.env` file where PHP loads the environment  variables from that to use in the configuration? looking quick i found this: https://github.com/vlucas/phpdotenv
* can you log the result of the upload instead of just the word upload? see for example: https://github.com/cloudinary-community/cloudinary-examples/blob/main/examples/node-video-upload/upload.js#L14

i think that's all and we shoudl be able to move forward!

**Comment by syedtalaljilani** [comment]
Ok sure

**Comment by syedtalaljilani** [comment]
all done @colbyfayock

**Comment by colbyfayock** [comment]
im not sure why but dotenv is no longer working for me ONLY for cloud name and api key, im trying to get help with it, ill report back

**Comment by colbyfayock** [comment]
nevermind apparently it was only the terminal session. i guess i shoudl start fresh each time 😅

**Comment by colbyfayock** [comment]
added a few tweaks here but good to go. thanks @syedtalaljilani

**Comment by colbyfayock** [comment]
@all-contributors please add @syedtalaljilani for code

**Comment by colbyfayock** [comment]
@syedtalaljilani congrats on the merged PR! since it was merged during Hacktoberfest, you're eligible for some free swag. Please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your Github username and a link to this PR where we'll follow up with you there.

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Comment by syedtalaljilani** [comment]
thank you @colbyfayock  for all your support and guidance and I have sent the email😊

**Pull request merged**
