### PR TITLE
Go examples add image overlay

### PR DESCRIPTION
**Pull request by saisumith770**
## Description 
Add go examples for image overlay

## Motivation
solves issue #78

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey thanks @saisumith770  - can you add a README for instructions on how to set it up and get started?

here's a similar example:

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/python-image-overlay

**Comment by saisumith770** [comment]
@colbyfayock I've added a README as requested.

**Comment by colbyfayock** [comment]
had a little trouble getting it working. im not familiar with Go so probably just user error, but i kept getting:
> go: download go1.23 for darwin/arm64: toolchain not available

i updated the go.mod file to use the same go version as the upload example:

https://github.com/cloudinary-community/cloudinary-examples/blob/main/examples/go-image-upload/go.mod

and that worked for me

im thinking someone who's familiar with Go will know how to manage this? 

but once i got it working it worked perfectly

thanks @saisumith770

**Comment by colbyfayock** [comment]
@all-contributors please add @saisumith770 for code

**Pull request merged**
