### PR TITLE
docs: dart image-overlay transformation

### PR DESCRIPTION
**Pull request by pwk50**
Fixes https://github.com/cloudinary-community/cloudinary-examples/issues/76

### Description
Add an example for image-overlay.

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey @pwk50 im new to dart, but im getting this error locally:

```
  dart-transformation-effects git:(dart-transformation) ✗ dart pub get
Resolving dependencies...
The current Dart SDK version is 2.19.5.

Because cloudinary_api >=1.0.1 depends on http ^1.0.0 and cloudinary_api >=1.0.0 <1.0.2 depends on cloudinary_url_gen
  ^0.10.0, cloudinary_api >=1.0.0 requires http ^1.0.0 or cloudinary_url_gen ^0.10.0.
And because http >=1.0.0 requires SDK version >=3.0.0 <4.0.0, cloudinary_api >=1.0.0 requires cloudinary_url_gen
  ^0.10.0.
So, because dart_transformation_effects depends on both cloudinary_url_gen ^1.0.0 and cloudinary_api ^1.0.0, version
  solving failed.
```

any idea why i might be getting that?

seems related to an http dependency perhaps?

**Comment by pwk50** [comment]
Hi @colbyfayock. I've updated the sdk constraint to `>=3.0.0` to comply with the http package's requirement. 
Also can you update your dart version if it's below 3.0.0 and try again.

FYI My dart version is 3.1.3 and I'm not getting this error.

**Comment by colbyfayock** [comment]
upgrade to v3 and it works great! thanks @pwk50

**Comment by colbyfayock** [comment]
@all-contributors please add @pwk50 for code

**Comment by colbyfayock** [comment]
@pwk50 congrats on the merged PR! since it was merged during Hacktoberfest, you're eligible for some free swag. Please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your Github username and a link to this PR where we'll follow up with you there.

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Pull request merged**
