### PR TITLE
Add nuxt upload widget example

### LINKED ISSUE #45: [Example] Nuxt - Upload Widget
Create a new example showing how to set up the Cloudinary Upload Widget in an Nuxt project.

See other frameworks for examples:

* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/nextjs-upload-widget-signed
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/react-upload-widget-preset
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/solid-upload-widget-preset
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/sveltekit-upload-widget-preset
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/vue-upload-widget-preset
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/remix-upload-widget-preset

### PR DESCRIPTION
**Pull request by akmittal**
## Description
Add Nuxt upload widget example

Resolve #45

### CODE REVIEW

**Comment by akmittal** [comment]
Resolves https://github.com/cloudinary-community/cloudinary-examples/issues/45

**Comment by colbyfayock** [comment]
hey @akmittal the example worked great!

2 requests:
- can you remove Nuxt Devtools? it seems to be conflicting with another project because of some kind of dependency issue, unless you can figure that out. simply running `yarn` to install triggers the issue for me
- can you update the README for instructions on getting the project running? see this example: https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/react-upload-widget-preset

**Comment by akmittal** [comment]
@colbyfayock 

Removed devtools and updated readme. Please take a look

**Comment by colbyfayock** [comment]
looks good, thanks @akmittal

**Comment by colbyfayock** [comment]
@all-contributors please add @akmittal for code

**Comment by colbyfayock** [comment]
@akmittal congrats on the merged PR! since it was merged during Hacktoberfest, you're eligible for some free swag. Please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your Github username and a link to this PR where we'll follow up with you there.

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Pull request merged**
