### PR TITLE
Add svelte-product-gallery example

### LINKED ISSUE #54: [Example] Svelte Product Gallery
Create a new example showing how to set up the Cloudinary Product Gallery in an Svelte project.

See other frameworks for examples:
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/react-product-gallery

### PR DESCRIPTION
**Pull request by geekysrm**
For Issue 54: Closes #54 
#### Created a new example showing how to set up the Cloudinary Product Gallery in an Svelte project.

- Used Vite for scaffolding the project
- UI looks exact same as React example

#### Screenshots
image

Let me know if I need to make any more changes.

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey @geekysrm looks great, can you do me a favor and add to the README instructions for spinning up the project locally for adding the tags used in the example to some images? or changing the tags in that location to match whats in the person's media library?

once done i can merge it in 🚀

**Comment by geekysrm** [comment]
@colbyfayock , have added some additional instructions. Let me know if they look good. Or I should add something else?

**Comment by colbyfayock** [comment]
I think that's perfect! thanks @geekysrm

**Comment by colbyfayock** [comment]
@all-contributors please add @geekysrm for code

@geekysrm congrats on the merged PR! since it was merged during Hacktoberfest, you're eligible for some free swag. Please email hacktoberfest@cloudinary.com with your Github username and a link to this PR where we'll follow up with you there.

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Pull request merged**
