### PR TITLE
java image upload

### LINKED ISSUE #71: [Example] Java - Uploading images
Create an example that shows how to upload images using the Cloudinary Java SDK

If it makes sense, this can be a script that can be executed via the terminal.

The example can be the same as the Node.js SDK example, but using the Java SDK.

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-image-upload

### PR DESCRIPTION
**Pull request by s-vamshi**
Closes #71 

Used Cloudinary Java SDK to upload image.

Here is the console output in eclipse.
image

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey @s-vamshi the upload worked perfectly!!

the only issue im seeing is it looks like it uploaded the same image multiple times for me

image
image

looking at the code, even though i dont know Java, it seems that the code is right? any ideas? looks like its listing the directory and looping through it 🤔

**Comment by s-vamshi** [comment]
> hey @s-vamshi the upload worked perfectly!!
> 
> the only issue im seeing is it looks like it uploaded the same image multiple times for me
> 
> image image
> looking at the code, even though i dont know Java, it seems that the code is right? any ideas? looks like its listing the directory and looping through it 🤔

@colbyfayock you are right! fixed it.

**Comment by colbyfayock** [comment]
worked perfectly! though i just wanted to give you a heads up it looks like you committed your CLOUDINARY_URL string 😢 

i've removed it from the code, however it won't remove it from git history

i would first of all recommend you resetting your API key and secret to be safe, to ensure no one compromises your account

but i will also run one of GitHub's tools to remove the file from git history and re-add it to try to remove it, however it may still show up within this Pull Request under the commits

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by colbyfayock** [comment]
@all-contributors please add @s-vamshi for code

**Comment by colbyfayock** [comment]
@s-vamshi congrats on the merged PR! since it was merged during Hacktoberfest, you're eligible for some free swag. Please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your Github username and a link to this PR where we'll follow up with you there.

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Comment by colbyfayock** [comment]
just following up to confirm that i was successfully able to remove it from the commits on the main branch, however, it still shows on this Pull Request

you can see this by browsing the change diffs in the commits: https://github.com/cloudinary-community/cloudinary-examples/commits/main

such as your bug fix appears empty because the file was removed, but it was re-added when i removed your sensitive data

again would advise that you reset your API Key and Secret to be safe

and make sure to email for your Hacktoberfest swag!

thanks

**Comment by s-vamshi** [comment]
> just following up to confirm that i was successfully able to remove it from the commits on the main branch, however, it still shows on this Pull Request
> 
> you can see this by browsing the change diffs in the commits: https://github.com/cloudinary-community/cloudinary-examples/commits/main
> 
> such as your bug fix appears empty because the file was removed, but it was re-added when i removed your sensitive data
> 
> again would advise that you reset your API Key and Secret to be safe
> 
> and make sure to email for your Hacktoberfest swag!
> 
> thanks

oops!! and yes I have removed the key and generated new one.
Also I would like to know if I should send mail for swags after all the PR's getting merged or for each PR?

**Comment by colbyfayock** [comment]
@s-vamshi you only need 1 valid PR to be eligble for swag!! so feel free to to email us whenever you'd like :)

but to also clarify, everyone is only eligible for 1 swag kit, no matter how many PRs you submit

**Pull request merged**
