### PR TITLE
Add Remix Product Gallery example

### LINKED ISSUE #52: [Example] Remix Product Gallery
Create a new example showing how to set up the Cloudinary Product Gallery in an Remix project.

See other frameworks for examples:
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/react-product-gallery

### PR DESCRIPTION
**Pull request by Insidiae**
Closes #52.

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey @Insidiae this example doesnt seem to be working for me, can you help me figure out whats going on?

to start, i was getting an error about `--manual` being included in the in the `dev` script, so removed that, and the server started, but i got a bunch of warnings, and the server won't render the page

image


using node v18

**Comment by Insidiae** [comment]
@colbyfayock Hmmm, I can't reproduce the error on my end (tried both PNPM and NPM to setup the project). What was the error you got about `--manual` in the `dev` script?

I used `pnpm dlx create-remix` to setup the example project (I also tried using `npx create-remix@latest` to recreate the same project to see if PNPM was causing the issue, but the relevant files all remained the same), i suspect the `--manual` is a new thing in Remix v2 🤔

I'm also using node v18 (v18.15.0 to be exact)

**Comment by colbyfayock** [comment]
ah i figured out the issue! you mentioning v2 made me think of it

i think its a dependency issue with the other remix project in there and using yarn workspaces. i need to think of a new strategy for that, but anyways, using npm install locally to that project worked

ill spin up a new ticket to migrate the other remix project to v2

thanks for the add @Insidiae

**Comment by colbyfayock** [comment]
@all-contributors please add @Insidiae for code

**Comment by colbyfayock** [comment]
@Insidiae congrats on the merged PR! since it was merged during Hacktoberfest, you're eligible for some free swag. Please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your Github username and a link to this PR where we'll follow up with you there.

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Pull request merged**
