### PR TITLE
Add: Python Text-Overlay Example

### LINKED ISSUE #118: [Example] Python - Adding an image text overlay builder
@colbyfayock 
While Cloudinary offers a Text Layer effect(Add a text layer on user defined co-ordinates), but I don't see any examples of it
I would like to add an example of the same

Here is a reference app I created using Streamlit & Cloudinary SDK: https://codingis4noobs2-expresso-main-9ocucm.streamlit.app/

Looking forward to your feedback!

### PR DESCRIPTION
**Pull request by codingis4noobs2**
Fixes #118

Added a Streamlit application that uses cloudinary, that allows user to place text over there image of any color, size, etc.

### CODE REVIEW

**Comment by codingis4noobs2** [comment]
@colbyfayock awaiting your feedback

**Comment by colbyfayock** [comment]
thanks @codingis4noobs2 

Streamlit seems pretty cool, but i'm realizing it probably makes more sense to make this as a streamlit example, not a python example (nuance there)

can you rename the directory to streamlit-transformations-effects (unless python is redundant there)

can you also create a file along the lines of `.streamlit/secrets.example.toml` to help people more easily figure out where to add the secrets and what secrets to add? i'm not familiar with the syntax so i myself am not quite sure how to get it (realizing i can look it up, it just makes it easier for anyone)

aside from that, worked well!

**Comment by codingis4noobs2** [comment]
@colbyfayock Thank you for the feedback

I have renamed the directory, and talking about `.streamlit/secrets.example.toml`, ig it can't be uploaded on GitHub
But I can definitely add a screenshot in the README.md file

**Comment by codingis4noobs2** [comment]
Done required changes🫡, awaiting feedback

**Comment by colbyfayock** [comment]
looks good, thanks @codingis4noobs2!!

**Comment by colbyfayock** [comment]
@all-contributors please add @codingis4noobs2 for code

**Comment by colbyfayock** [comment]
congrats on the merged PR! since it was merged during Hacktoberfest, you're eligible for some free swag. Please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your Github username and a link to this PR where we'll follow up with you there.

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Pull request merged**
