### PR TITLE
docs: implement image overlay  with Cloudinary Ruby/Rails SDK

### LINKED ISSUE #77: [Example] Ruby - Adding an image as an overlay
Add an example as an executable script that adds an image as an overlay to an existing image in Ruby.

You can start off by replicating this folder and example from Node:

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-transformations-effects

Particularly the image-overlay.js file, but in Ruby.

### PR DESCRIPTION
**Pull request by error9098x**
closes #77 
fixes #77 

I have implemented the image overlay for Ruby, please check it out @colbyfayock .
Looking forward to any suggestions 😁

### CODE REVIEW

**Comment by colbyfayock** [comment]
worked perfectly @error9098x!

2 things:
* is there some kind of way to install all the dependnecies without manually installing each package? iirc is a Gemfile possible? think the context of me using that was rails though
* i think the URL in the README is using your cloud name right? 
```
![Image](https://res.cloudinary.com/dqps1qwko/image/upload/c_fill,h_850,w_700/h_200,l_samples:breakfast,w_200/fl_layer_apply,g_north_east,x_400,y_400/v1/samples/smile.jpg)
```
you can feel free to just remove that from the README, while nice, i dont want to be referencing your account, particularly so its not wasting usage for you!

**Comment by error9098x** [comment]
1. I tried gemfile way but didn't worked for me the first time, I will try again and check.
2. Sure, I will remove the image_url, do you want me to add a sample folder and place the image in the sample folder to show that in the readme or just leave that part completely?

**Comment by error9098x** [comment]
I have added the gemfile and removed the image url.

**Comment by colbyfayock** [comment]
I think what you have here looks great! I need to think of a good way to handle the sample images but i'll figure that out later :) for now i think this is perfect

thanks @error9098x

**Comment by colbyfayock** [comment]
@all-contributors please add @error9098x for code

**Comment by colbyfayock** [comment]
@error9098x  congrats on the merged PR! since it was merged during Hacktoberfest, you're eligible for some free swag. Please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your Github username and a link to this PR where we'll follow up with you there.

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Pull request merged**
