### PR TITLE
Add .NET server-side examples

### PR DESCRIPTION
**Pull request by adityaoberai**
## Description

Added .NET server-side examples to upload images and videos

## Related Issue

https://github.com/cloudinary-community/cloudinary-examples/issues/62

### CODE REVIEW

**Comment by adityaoberai** [comment]
cc: @colbyfayock

**Comment by colbyfayock** [comment]
looks great, thanks @adityaoberai

**Comment by colbyfayock** [comment]
@all-contributors please add @adityaoberai for code

**Comment by colbyfayock** [comment]
@adityaoberai congrats on the merged PR! since it was merged during Hacktoberfest, you're eligible for some free swag. Please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your Github username and a link to this PR where we'll follow up with you there.

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Pull request merged**
