### PR TITLE
python image upload

### LINKED ISSUE #70: [Example] Python - Uploading images
Create an example that shows how to upload images using the Cloudinary Python SDK

If it makes sense, this can be a script that can be executed via the terminal.

The example can be the same as the Node.js SDK example, but using the Python SDK.

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-image-upload

### PR DESCRIPTION
**Pull request by s-vamshi**
Closes #70 
Used Cloudinary Python SDK to upload image.

Here is the console output in terminal.

image

### CODE REVIEW

**Comment by colbyfayock** [comment]
this worked great! 2 quick notes / questions:
* i had to use `python3` in order to run the script on my machine (Mac), can we just add a note in the README that you may have to use `python3`?
* is there any kind of solution where running 1 command installs all dependencies? if you're familiar with the javascript world, thats typically in a package.json, where you run npm install. is there something similar thats common? or is it common to install the dependencies manually like in the README?

**Comment by colbyfayock** [comment]
@s-vamshi just looked it up and that sounds right. have you done that before? woudl it make sense to add?

**Comment by s-vamshi** [comment]
@colbyfayock yes I have worked on it before.
I have committed changes can you try once

**Comment by colbyfayock** [comment]
worked great ! thanks @s-vamshi

**Pull request merged**
