### PR TITLE
Add Go image upload example

### LINKED ISSUE #67: [Example] Go - Uploading images
Create an example that shows how to upload images using the Cloudinary Go SDK

If it makes sense, this can be a script that can be executed via the terminal.

The example can be the same as the Node.js SDK example, but using the Go SDK.

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-image-upload

### PR DESCRIPTION
**Pull request by rahul1995**
Closes #67 

Used Cloudinary Go SDK to upload image.

Here is the console output in terminal -
image

### CODE REVIEW

**Comment by rahul1995** [comment]
Updated the README file.

**Comment by colbyfayock** [comment]
worked perfectly! thanks @rahul1995

**Comment by colbyfayock** [comment]
@all-contributors please add @rahul1995 for code

**Comment by colbyfayock** [comment]
@rahul1995 congrats on the merged PR! since it was merged during Hacktoberfest, you're eligible for some free swag. Please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your Github username and a link to this PR where we'll follow up with you there.

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Pull request merged**
