### PR TITLE
Feat/upgrade clduploadwidget signed and captions

### PR DESCRIPTION
**Pull request by max-programming**
This pull request includes upgrading two examples

- nextjs-clduploadwidget-signed
- nextjs-clduploadwidget-captions

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey @max-programming  this is looking good, push a few style/cleanup tweaks

i think the only thing id like a little different is the app router Uploader component

the recommendation that I've been using to get around the client components is to create a light wrapper around the component

see example: https://next.cloudinary.dev/nextjs-14#app-router-app

I think that would be preferable so that you can includ the result UI inside of the page file simlar to what you have in the pages directory

wdyt?

**Comment by max-programming** [comment]
@colbyfayock The reason I did not create a wrapper component for both `CldUploadWidget` and `CldImage` is because there's `useState` being used. Which eventually needs a `"use client"` on top.

So I put them together inside one client component.

**Comment by max-programming** [comment]
@colbyfayock Done ✅

**Comment by colbyfayock** [comment]
looks great, thanks @max-programming

**Pull request merged**
