### PR TITLE
Add product gallery example for Solid.js

### LINKED ISSUE #53: [Example] Solid Product Gallery
Create a new example showing how to set up the Cloudinary Product Gallery in an Solid project.

See other frameworks for examples:
* https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/react-product-gallery

### PR DESCRIPTION
**Pull request by hirenchauhan2**
Closes #53

### CODE REVIEW

**Comment by colbyfayock** [comment]
hey @hirenchauhan2 can you update the README to say solid instead of Svelte and can you also address this similar feedback for adding instructions for the tagging system used for pulling in assets?

https://github.com/cloudinary-community/cloudinary-examples/pull/55#issuecomment-1743731958

**Comment by hirenchauhan2** [comment]
Sure, will do.

**Comment by hirenchauhan2** [comment]
Hi @colbyfayock I've added the changes in the readme. Let me know if that suffices or need to add more.

**Comment by colbyfayock** [comment]
looks good to me, thanks @hirenchauhan2

**Comment by colbyfayock** [comment]
@all-contributors please add @hirenchauhan2 for code

congrats on the merged PR! since it was merged during Hacktoberfest, you're eligible for some free swag. Please email [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your Github username and a link to this PR where we'll follow up with you there.

https://cloudinary.com/blog/hacktoberfest-celebrate-open-source-sdks

**Pull request merged**
