### PR TITLE
feat: Add dart image upload sample

### LINKED ISSUE #69: [Example] Dart - Uploading images
Create an example that shows how to upload images using the Cloudinary Dart SDK

If it makes sense, this can be a script that can be executed via the terminal.

The example can be the same as the Node.js SDK example, but using the Dart SDK.

https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/node-image-upload

### PR DESCRIPTION
**Pull request by adityaoberai**
## Description

Added Dart server-side examples to upload images

## Related Issue

Fixes #69

### CODE REVIEW

**Comment by adityaoberai** [comment]
@colbyfayock the PR is ready to review

**Comment by colbyfayock** [comment]
hey @adityaoberai the script worked perfectly!!

what do you think about adding the ability (at least in the form of docs) to install dependencies with `dart pub get`? in my mind its kinda like an npm install

also any thoughts on adding .env support instead of the exports?

this other dart example someone provided has those things, curious about if you think its worth adding: https://github.com/cloudinary-community/cloudinary-examples/tree/main/examples/dart-transformation-effects

**Comment by adityaoberai** [comment]
That's a great idea @colbyfayock! I'll make these changes :)

**Comment by adityaoberai** [comment]
@colbyfayock made the update

**Comment by colbyfayock** [comment]
worked perfectly @adityaoberai!! 

thanks for your help 🚀

**Pull request merged**
